services:
  flight-monitor:
    build:
      context: ./frontend
      dockerfile: Containerfile
    develop:  
      watch:
        - path: ./frontend/static
          action: sync
          target: /home/fritz/static    
    ports:
      - "4000:8080" 

  flight-data-provider:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8080:8080"
