services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "4000:8080" 

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8080:8080"
